name: mir-kiosk-scummvm
adopt-info: scummvm
summary: ScummVM packaged as a mir-kiosk snap
description: ScummVM packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core20
license: GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep EGL
  LD_LIBRARY_PATH: $SNAP/graphics/lib
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  # Prep SDL
  SDL_VIDEODRIVER: wayland

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/games:
    bind: $SNAP/usr/games
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio

plugs:
  wayland:
  opengl:
  audio-playback:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

apps:
  daemon:
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/scummvm-launch
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-scummvm:
    command-chain:
      - bin/wayland-launch
    command: bin/scummvm-launch
    desktop: usr/share/applications/scummvm.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  glue:
    plugin: dump
    source: glue

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland graphics-core20 audio-playback
    stage-packages:
      - inotify-tools

  scummvm:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `LANG=C apt-cache policy scummvm | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    override-build: |
      snapcraftctl build
      sed -i s:Icon=scummvm:Icon=/usr/share/icons/hicolor/scalable/apps/scummvm.svg:g $SNAPCRAFT_PART_INSTALL/usr/share/applications/scummvm.desktop

    stage-packages:
      - scummvm
      - fluidsynth
      - timidity
      - beneath-a-steel-sky
      - drascula
      - flight-of-the-amazon-queen
      - lure-of-the-temptress

  sdl2:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  # scummvm needs libGLU which mesa supplies. But it isn't included in graphics-core20.
  mesa:
    plugin: nil
    stage-packages:
      - libglu1-mesa

  wayland:
    plugin: nil
    stage-packages:
      - libwayland-egl1

  cleanup:
    after: [scummvm, mir-kiosk-snap-launch, sdl2, wayland, glue, icons, mesa]
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
