name: mir-kiosk-scummvm
adopt-info: scummvm
summary: ScummVM packaged as a mir-kiosk snap
description: ScummVM packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core20
license: GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  # Prep SDL
  SDL_VIDEODRIVER: wayland

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/games:
    bind: $SNAP/usr/games

plugs:
  wayland:
  opengl:
  audio-playback:
  pulseaudio:
  alsa:

apps:
  daemon:
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/scummvm-launch
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-scummvm:
    command-chain:
      - bin/wayland-launch
    command: bin/scummvm-launch
    desktop: usr/share/applications/scummvm.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  glue:
    plugin: dump
    source: glue

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl audio-playback pulseaudio alsa wayland
    stage-packages:
      - inotify-tools

  scummvm:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `LANG=C apt-cache policy scummvm | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    override-build: |
      snapcraftctl build
      sed -i s:Icon=scummvm:Icon=/usr/share/icons/hicolor/scalable/apps/scummvm.svg:g $SNAPCRAFT_PART_INSTALL/usr/share/applications/scummvm.desktop

    stage-packages:
      - scummvm
      - fluidsynth
      - timidity
      - beneath-a-steel-sky
      - drascula
      - flight-of-the-amazon-queen
      - lure-of-the-temptress

  sdl2:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa

  wayland:
    plugin: nil
    stage-packages:
      - libwayland-client0
